# Generated by Django 6.0.4 on 2026-04-16 19:00

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier', primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('email', models.EmailField(help_text='Primary email for login and notifications', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Used for demographic insights and age verification', null=True)),
                ('gender_identity', models.CharField(blank=True, choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say'), ('other', 'Other')], help_text='Self-identified gender', max_length=30, null=True)),
                ('gender_identity_custom', models.CharField(blank=True, help_text="If 'Other' selected, specify here", max_length=100)),
                ('profile_picture', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='profile_pictures/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text='Short bio (max 500 characters)', max_length=500)),
                ('is_verified', models.BooleanField(default=False, help_text='Email/identity verified status')),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone for 2FA', max_length=10)),
                ('consensus_score', models.IntegerField(default=0, help_text='Total trust score across all clubs', validators=[django.core.validators.MinValueValidator(0)])),
                ('learning_level', models.IntegerField(default=1, help_text='Current knowledge tier (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', help_text='User experience level in trading', max_length=20)),
                ('total_reels_watched', models.PositiveIntegerField(default=0, help_text='Count of Fin-Pulse reels viewed')),
                ('total_votes_cast', models.PositiveIntegerField(default=0, help_text='Total participation in club votes')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='User notification settings (email, push, SMS)')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, help_text='Profile visibility and data sharing preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['username'], name='users_user_usernam_65d164_idx'), models.Index(fields=['is_verified'], name='users_user_is_veri_9ce429_idx'), models.Index(fields=['created_at'], name='users_user_created_cf865c_idx')],
            },
        ),
    ]
