# Generated by Django 6.0.4 on 2026-04-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_finova_id_user_individual_virtual_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.CharField(blank=True, help_text="User's PAN card for verification", max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
