# Generated by Django 6.0.4 on 2026-04-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCache',
            fields=[
                ('symbol', models.CharField(help_text='e.g. AAPL, TSLA, RELIANCE.NS', max_length=20, primary_key=True, serialize=False)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('percent_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Cache',
                'verbose_name_plural': 'Stock Caches',
                'ordering': ['symbol'],
            },
        ),
    ]
