# Generated by Django 6.0.4 on 2026-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcache',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='book_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='debt_to_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='dividend_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='fundamentals_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='news_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stored news items array', null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='pb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='pe_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='roce',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
