# Generated by Django 6.0.4 on 2026-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stockcache_beta_stockcache_book_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcache',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='last_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='ltq_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stockcache',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
