# Generated by Django 6.0.4 on 2026-04-17 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_one', models.ForeignKey(help_text='First participant in the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_one', to=settings.AUTH_USER_MODEL)),
                ('participant_two', models.ForeignKey(help_text='Second participant in the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message text content', max_length=5000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('stock_card', 'Stock Card'), ('news_card', 'News Card')], default='text', max_length=15)),
                ('stock_symbol', models.CharField(blank=True, help_text='Stock symbol if message is a stock card (auto-parsed from /stocks template)', max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='chat.conversation')),
                ('reply_to', models.ForeignKey(blank=True, help_text='Reply to another message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.directmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'direct message',
                'verbose_name_plural': 'direct messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_one', 'updated_at'], name='chat_conver_partici_6c0be5_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_two', 'updated_at'], name='chat_conver_partici_ca465e_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='unique_conversation_pair'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_direct_convers_66c4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_direct_sender__d96db3_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['is_read'], name='chat_direct_is_read_d7320c_idx'),
        ),
    ]
