# Generated by Django 6.0.4 on 2026-04-17 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finova_id',
            field=models.CharField(default='DEF', editable=False, help_text='Unique 6-char Finova ID (e.g. FHW397) for user lookup', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='individual_virtual_capital',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Individual capital user can allocate to group pools', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['finova_id'], name='users_user_finova__639953_idx'),
        ),
    ]
