# Generated by Django 6.0.4 on 2026-04-17 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(help_text='Ticker symbol (e.g. AAPL, RELIANCE)', max_length=20)),
                ('stock_name', models.CharField(blank=True, help_text='Full company name', max_length=200)),
                ('discussion_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], help_text='Proposed action: buy, sell, or hold', max_length=10)),
                ('reasoning', models.TextField(help_text='Why the proposer thinks this trade should happen', max_length=5000)),
                ('status', models.CharField(choices=[('open', 'Open for Discussion'), ('pooling', 'Waiting for Capital Funding'), ('voting', 'Voting in Progress'), ('executed', 'Trade Executed'), ('expired', 'Expired'), ('rejected', 'Rejected by Vote'), ('cancelled', 'Cancelled (Underfunded/Expired)')], default='open', max_length=10)),
                ('min_engagement_to_unlock_vote', models.PositiveIntegerField(default=3, help_text='Minimum number of member comments before voting unlocks')),
                ('engagement_count', models.PositiveIntegerField(default=0, help_text='Current number of comments on this discussion')),
                ('required_capital', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of pooled capital required to execute this trade', max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the POOLING or VOTING phase auto-cancels if underfunded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discussion',
                'verbose_name_plural': 'discussions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment text', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='groups.discussion')),
            ],
            options={
                'verbose_name': 'discussion comment',
                'verbose_name_plural': 'discussion comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finova_id', models.CharField(editable=False, help_text='Unique group ID (e.g. GRP-A4F821)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Group name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Group description for the about section', max_length=1000)),
                ('guidelines', models.TextField(blank=True, help_text='Group rules & investment guidelines', max_length=2000)),
                ('group_photo', models.ImageField(blank=True, help_text='Group avatar/photo', null=True, upload_to='group_photos/%Y/%m/')),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', help_text='Risk assessment level for this group', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=10, help_text='Maximum number of members allowed (2-50)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='groups.group'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', help_text='Member role within the group', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group member',
                'verbose_name_plural': 'group members',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message text content', max_length=5000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('stock_card', 'Stock Card'), ('news_card', 'News Card'), ('system', 'System Message')], default='text', max_length=15)),
                ('stock_symbol', models.CharField(blank=True, help_text='Stock symbol if message is a stock card (auto-parsed from /stocks template)', max_length=20, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.group')),
                ('reply_to', models.ForeignKey(blank=True, help_text='Reply thread parent message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='groups.groupmessage')),
                ('sender', models.ForeignKey(blank=True, help_text='Null for system messages', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group message',
                'verbose_name_plural': 'group messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='groups.group')),
            ],
            options={
                'verbose_name': 'group wallet',
                'verbose_name_plural': 'group wallets',
            },
        ),
        migrations.CreateModel(
            name='TradePoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quorum_percentage', models.PositiveIntegerField(default=60, help_text='Percentage of members needed to approve (default 60%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('voting_deadline', models.DateTimeField(help_text='Current deadline (may be reduced by Turbo mode)')),
                ('original_deadline', models.DateTimeField(help_text='Original 24-hour deadline before any Turbo reduction')),
                ('reduced_deadline', models.DateTimeField(blank=True, help_text='Deadline after Turbo-Reduction (90% time drop)', null=True)),
                ('turbo_reduction_applied', models.BooleanField(default=False, help_text='Whether 100% participation triggered Turbo mode')),
                ('status', models.CharField(choices=[('active', 'Active'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('result_buy_count', models.PositiveIntegerField(default=0)),
                ('result_sell_count', models.PositiveIntegerField(default=0)),
                ('result_hold_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='groups.discussion')),
            ],
            options={
                'verbose_name': 'trade poll',
                'verbose_name_plural': 'trade polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10)),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='groups.tradepoll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'ordering': ['cast_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('locked', 'Locked for Trade'), ('refund', 'Refunded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, help_text='Related ID (e.g. Poll/Discussion ID)', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='groups.groupwallet')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['finova_id'], name='groups_grou_finova__70b626_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='groups_grou_is_acti_044fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='groups_grou_created_b17bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['group', 'status'], name='groups_disc_group_i_db30fa_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['stock_symbol'], name='groups_disc_stock_s_533efe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'created_at'], name='groups_grou_group_i_7da147_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['message_type'], name='groups_grou_message_578879_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter')},
        ),
    ]
