# Generated by Django 6.0.4 on 2026-04-17 16:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='minimum_trust_score',
            field=models.IntegerField(default=0, help_text='Minimum consensus_score required to join or send a join request.'),
        ),
        migrations.AddField(
            model_name='group',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If True, users must send a join request to be approved by admins.'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message to the group admins', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'join request',
                'verbose_name_plural': 'join requests',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
