# Generated by Django 6.0.4 on 2026-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_minimum_trust_score_group_requires_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepoll',
            name='reduced_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline after Turbo-Reduction (95% time drop)', null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('locked', 'Locked for Trade'), ('refund', 'Refunded'), ('trade_buy', 'Trade Execution (Buy)'), ('trade_sell', 'Trade Execution (Sell)')], max_length=20),
        ),
    ]
