# Generated by Django 6.0.4 on 2026-04-18 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('average_buy_price', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='groups.group')),
            ],
            options={
                'verbose_name': 'group holding',
                'verbose_name_plural': 'group holdings',
                'unique_together': {('group', 'stock_symbol')},
            },
        ),
    ]
