# Generated by Django 6.0.4 on 2026-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='polled_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The market price at the moment the discussion was proposed', max_digits=12),
        ),
    ]
